name = "newsnow-project"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "c8a9fa8b-5280-421b-a284-714d4aab583d"      # 替换为你创建的数据库 ID
